# Generated by Django 4.1.3 on 2022-12-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPhase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(default='', max_length=1000)),
                ('patientAge', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('patientOrigin', models.CharField(default='', max_length=1000)),
                ('phoneNumber', models.CharField(default='', max_length=1000)),
                ('hospitalSource', models.CharField(default='', max_length=1000)),
                ('whyRkch', models.CharField(default='', max_length=1000)),
                ('issueWithFindingRkch', models.CharField(default='', max_length=1000)),
                ('issueWithFindingRkchReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('experienceInReg', models.CharField(default='', max_length=1000)),
                ('experienceInRegReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('experienceInAdmission', models.CharField(default='', max_length=1000)),
                ('experienceInAdmissionReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('parking', models.CharField(default='', max_length=1000)),
                ('parkingReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('finance', models.CharField(default='', max_length=1000)),
                ('financeReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPhase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(default='', max_length=1000)),
                ('doctor', models.CharField(default='', max_length=1000)),
                ('doctorReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('staff', models.CharField(default='', max_length=1000)),
                ('staffReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('tests', models.CharField(default='', max_length=1000)),
                ('testsReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPhase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(default='', max_length=1000)),
                ('discharge', models.CharField(default='', max_length=1000)),
                ('dischargeReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('billing', models.CharField(default='', max_length=1000)),
                ('billingReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('continuum', models.CharField(default='', max_length=1000)),
                ('continuumReason', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
